jgromes/RadioLib

- examples/SX126x/SX126x_FSK_Modem/SX126x_FSK_Modem.ino
- keywords.txt
- src/modules/SX126x.cpp
- src/modules/SX126x.h
Add setSyncBits for possibility to set the sync word length in bits
> Add setSyncBits for SX126x

- README.md
> Add STM32VL-Discovery to tested platforms

- src/modules/CC1101/CC1101.cpp
- src/modules/CC1101/CC1101.h
Refers to https://github.com/jgromes/RadioLib/issues/92
> [CC1101] Added setOOK(bool enableOOK)

- src/modules/RF69/RF69.cpp
- src/modules/SX126x/SX126x.cpp
- src/modules/SX127x/SX1272.cpp
- src/modules/SX127x/SX1278.cpp
- src/modules/XBee/XBee.cpp
- src/modules/nRF24/nRF24.cpp
See https://github.com/jgromes/RadioLib/issues/126 for context.
> Swap delayMicroseconds() to delay where appropriate

- keywords.txt
- src/modules/RF69/RF69.cpp
- src/modules/RF69/RF69.h
- src/modules/SX127x/SX127x.cpp
- src/modules/SX127x/SX127x.h
- SX127X enable/disable BitSync
- RF69::enableContinuousModeBitSync()
- RF69::setOokFixedThreshold
- RF69::setOokFixedThreshold()
> RF69 and SX127X new functions

- src/modules/CC1101/CC1101.h
- src/modules/SX127x/SX127x.h
some minor doc issues, no code changes.
> Documentation updates

- src/modules/RF69/RF69.cpp
Used a similar approach to other modules, (CC1101/RFM95).
Tested by looping through all valid values and comparing register after setting. Also tested invalid values.
Fixes #497
> Fix setRxBandwidth by calculating mantissa and exponent, rather than comparing floats

- src/modules/SX127x/SX127x.cpp
- src/modules/SX127x/SX127x.h
proposed solution for [[SX1276] Request to add setCrcFiltering(bool crcOn = true)](https://github.com/jgromes/RadioLib/issues/524)
> [SX127x] added setCrcFiltering()

- src/modules/SX127x/SX127x.cpp
- src/modules/SX127x/SX127x.h
New function in SX127x module that returns the time on air of a lora packet.
> RadioLib - getTimeOnAir for SX127x modules

- src/TypeDef.h
- src/modules/RF69/RF69.cpp
- src/modules/RF69/RF69.h
- src/modules/SX127x/SX127x.cpp
- src/modules/SX127x/SX127x.h
For RF69 and SX127x families of chips
> Introduce the setRSSIThreshold method

- src/modules/LLCC68/LLCC68.h
- src/modules/SX126x/SX1262.h
- src/modules/SX126x/SX1268.h
- src/modules/SX126x/SX126x.cpp
- src/modules/SX126x/SX126x.h
- src/modules/SX128x/SX128x.h
These are two small issues I noticed while working on #588 that were separate from that issue, so best put into their own PR. These are fairly trivial fixes, I think. See commit messages for details.
> [SX126x] Fix comments & Dio2 for FSK

- .github/workflows/uncrustify.yml
- uncrustify.cfg
Enforce code style by using uncrustify
> Added Uncrustify

- src/BuildOpt.h
- src/Module.cpp
- src/Module.h
- src/modules/CC1101/CC1101.cpp
- src/modules/RF69/RF69.cpp
- src/modules/RFM9x/RFM95.cpp
- src/modules/RFM9x/RFM96.cpp
- src/modules/SX1231/SX1231.cpp
- src/modules/SX126x/SX126x.cpp
- src/modules/SX127x/SX1272.cpp
- src/modules/SX127x/SX1278.cpp
- src/modules/SX127x/SX127x.cpp
- src/modules/SX128x/SX128x.cpp
- src/modules/Si443x/Si4430.cpp
- src/modules/Si443x/Si4431.cpp
- src/modules/Si443x/Si4432.cpp
- src/modules/Si443x/Si443x.cpp
- src/modules/nRF24/nRF24.cpp
- src/protocols/AX25/AX25.cpp
- src/protocols/AX25/AX25.h
- src/protocols/Hellschreiber/Hellschreiber.cpp
- src/protocols/Hellschreiber/Hellschreiber.h
- src/protocols/Morse/Morse.cpp
- src/protocols/Morse/Morse.h
- src/protocols/Pager/Pager.cpp
- src/protocols/Pager/Pager.h
- src/protocols/PhysicalLayer/PhysicalLayer.cpp
- src/protocols/PhysicalLayer/PhysicalLayer.h
- src/protocols/RTTY/RTTY.cpp
- src/protocols/RTTY/RTTY.h
I confirm that it works on generic build, but I didn't tested it on Arduino.
> Fix generic build

- .github/workflows/main.yml
This makes the workflow lighter and more readable and allows to add more easily newer platforms in the future (like raspberrypi, by simply adding other parameters like `isarduino` in matrix and adapting the end)
> improve build workflow for better flexibility

- examples/NonArduino/Tock/main.cpp
Somehow this slipped through in https://github.com/jgromes/RadioLib/pull/793 and then I kept testing a more complex example
> Tock: Fixup build failure

- examples/NonArduino/Tock/toolchain-arm-none-eabi.cmake
Instead of hard coding paths, let's instead try to find the toolchain from the users PATH.
> Tock: toolchain: Try to be smarter about finding toolchains

- src/modules/CC1101/CC1101.cpp
When using a blocking receive, I was getting non-sensical packet length and garbage data, whereas IRQ mode was working fine. This was happening despite what looked like a workaround for this in the code which would read the length twice.
I tracked it down to the receive function trying to read the data too early, before the packet had even been received. The receive function would wait for the GDO0 pin to become low, then assume the packet was ready and read off the data.
However, the GD0 pin is set by the `startReceive` as inverted and, according to the datasheet, in a mode which "asserts when sync word has been received, and de-asserts at the end of the packet". In other words, taking into account the inversion, GDO0 becomes low at the start of the packet and high at the end of it. …
> [CC1101] Correctly wait for packet end on blocking receive.

- src/protocols/LoRaWAN/LoRaWAN.cpp
This PR contains the bug fix proposed by @StevenCellist in #950.
I tested the bug fix in a live environment and was able to send more than 50 messages.
> [LoRaWAN] Fix fcntUp wrap-around after 50 transmissions

- .github/workflows/codeql-analysis.yml
- .github/workflows/cppcheck.yml
- .github/workflows/doxygen.yml
- .github/workflows/main.yml
* Added cppcheck action
* Resolved outdated actions
> Static check

- src/Module.h
- src/modules/CC1101/CC1101.h
- src/modules/RF69/RF69.h
- src/modules/SX126x/STM32WLx_Module.cpp
- src/modules/SX126x/SX126x.h
- src/modules/SX127x/SX1272.h
- src/modules/SX127x/SX127x.h
- src/modules/nRF24/nRF24.h
- src/protocols/AFSK/AFSK.h
- src/protocols/APRS/APRS.h
- src/protocols/BellModem/BellModem.h
- src/protocols/ExternalRadio/ExternalRadio.h
- src/protocols/LoRaWAN/LoRaWAN.h
- src/protocols/PhysicalLayer/PhysicalLayer.h
- src/protocols/Print/Print.cpp
- src/protocols/Print/Print.h
Bunch of fixes to doxygen generation (e.g. missing docs, incorrectly named parameters etc.)
> [Doxygen] Warnings fixes

- .github/workflows/main.yml
- examples/NonArduino/Tock/CMakeLists.txt
- examples/NonArduino/Tock/README.md
Remove the libtock-c submodule to fix https://github.com/jgromes/RadioLib/issues/1091
> examples/NonArduino/Tock: Remove libtock-c submodule

- .github/workflows/main.yml
- examples/NonArduino/Tock/CMakeLists.txt
- examples/NonArduino/Tock/README.md
- examples/NonArduino/Tock/libtockHal.h
Update to use the latest libtock-c functions.
> examples/NonArduino/Tock: Update to the latest libtock-c API

- src/TypeDef.h
- src/modules/CC1101/CC1101.cpp
- src/modules/CC1101/CC1101.h
Same as last pull request with updated error handling.
Tested with ESP32 and PlatformIO environment.
> Method SetBitrateTolerance added for CC1101, Updated error handling

- src/modules/SX128x/SX128x.cpp
- src/modules/SX128x/SX128x.h
Add getRssi() without packet like SX1262 works. Tested works with SX1280
> getRssi(false) without packet  

- src/modules/SX123x/SX1231.cpp
- src/modules/SX123x/SX1231.h
- src/modules/SX123x/SX1233.cpp
> add chip revision number for Semtech SX123xH

- src/modules/SX128x/SX128x.cpp
> [SX128x] fix for invalid GSFK sync words order

- CMakeLists.txt
- examples/NonArduino/Pico/CMakeLists.txt
- src/hal/RPiPico/PicoHal.cpp
- src/hal/RPiPico/PicoHal.h
This PR moves helper functions from PicoHal header to a separate file, as alternative solution to #1506
> [HAL] Rpi pico hal fix
